<?php
/**
* Message translations.
*
* This file is automatically generated by 'yiic message' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE, this file must be saved in UTF-8 encoding.
*/

// the comment under each translation item indicates which files that message
// is used in. And the number in braces tells how many times it appears in
// that file (omitted if only once).

return array(
    'Congratulations! You have successfully created your Yii web application.' => '', 
    // protected\views\site\index.php
    'Congratulations! You have successfully created your Yii application.' => '@@Congratulation.@@', 
    'Please fill out the following form with your login credentials:' => 'adfsdfsdfsdf', 
    // protected\views\site\error.php
    // protected\views\site\login.php (2)

);
	